pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'python3 -m py_compile pythoncode/add2vals.py pythoncode/calc.py'
                stash(name: 'compiled-results', includes: 'pythoncode/*.py*')
                sh 'ls -l pythoncode'
            }
        }
        stage('Test') { 
            steps {
                sh 'pytest-3 --junit-xml test-reports/results.xml pythoncode/test_calc.py' 
                sh 'cat test-reports/results.xml'
            }
        }
    }
    post {
        always {
            junit 'test-reports/results.xml' 
        }
    }
}
